name: tethys-contest
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - django=5.2
  - tethys-platform
  - pandas
  - numpy
  - plotly
  - requests
  - ecmwf-opendata
  - cfgrib
  - eccodes
  - pytest
  - setuptools>=68
  - wheel
  - pip
